services:
  epexpredictor:
    #image: ghcr.io/b3nn0/epexpredictor:main # or :v0.0.1, ...
    build: .
    # restart: unless-stopped
    ports:
      - "8000:80"
    slug: epex_price_predictor
    volumes:
      - ./data:/data
    
    environment:
      - EPEXPREDICTOR_DATADIR=/data/

