services:
  epexpredictor:
    #image: ghcr.io/b3nn0/epexpredictor:main # or :v0.0.1, ...
    build: .
    # restart: unless-stopped
    ports:
      - "8000:80"

    volumes:
      - ./data:/data
    
    environment:
      - EPEXPREDICTOR_DATADIR=/data/
      # It is highly recommended that you request Entso-E API access and configure the key here. It serves as
      # 1. It serves as an additional source for price data, in case energy-charts is down
      # 2. It is required to source prices fore some regions (e.g. sweden)
      # 3. It offers an electical load forecast, significantly improving model performance
      # - EPEXPREDICTOR_ENTSOE_API_KEY=

